[package]
name = "game"
version = "0.1.0"
authors = ["Devin Brite <devin@dwbrite.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3


[dependencies]
bevy = { version = "0.18.1", default-features = false, features = ["2d", "bevy_dev_tools", "bevy_ui_debug", "ui", "gamepad", "asset_processor"] }
bevy_rapier2d = { version = "*", features = [ "simd-stable", "debug-render-2d" ] }
bevy_aseprite_ultra = { version = "0.8.2",  features = ["asset_processing"]}
heapless = "0.9.3"

ir = { path = "../ir" }
enum-map = "2.7.3"


[build-dependencies]
ir-parser = { path = "../ir-parser" }
